name: Deploy to AWS EC2
 
on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up Node.js (If using Node.js)
      uses: actions/setup-node@v3
      with:
        node-version: '16'
 
    - name: Install dependencies
      run: npm install  # Adapt this to your project
 
    - name: Run tests (Optional)
      run: npm test  # Adapt this to your project
 
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_EC2_HOST }}  # Add this to your GitHub Secrets
        username: ${{ secrets.AWS_EC2_USER }}  # Add this to your GitHub Secrets
        key: ${{ secrets.AWS_EC2_KEY }}  # Add your SSH private key to GitHub Secrets
        script: |
          cd C:\Users\LENOVO\OneDrive\Desktop\Miraffra\Internship-Mlops-Project
          git pull origin main
          npm install  # Adapt this to your project
          pm2 restart all  # Restart your Node.js app, if using PM2
